"""
Django settings for Kurikulum project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

#import django_heroku
#import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^f(0=o4)2b_wu#$w-^*+8&($h0su@92jn0d%5ut5bhy(p$h@a='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
}


# ALLOWED_HOSTS = [
#ALLOWED_HOSTS = ['Kurikulum.herokuapp.com', 'localhost', '127.0.0.1']
# d019-2001-448a-5080-2194-6cfb-50e4-4107-b36d.ngrok-free.app
# https://6a43-2001-448a-5080-3721-c131-5ef4-5a44-b656.ngrok-free.app
# ]

ALLOWED_HOSTS = ['localhost', '127.0.0.1',
                 '6a43-2001-448a-5080-3721-c131-5ef4-5a44-b656.ngrok-free.app',
                 'belajarCoding81.pythonanywhere.com']

CSRF_TRUSTED_ORIGINS = [
    'https://6a43-2001-448a-5080-3721-c131-5ef4-5a44-b656.ngrok-free.app']

# 0910-182-3-197-81.ngrok-free.app
# https://0910-182-3-197-81.ngrok-free.app

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'obe',
    'rest_framework',
    'django_select2',
    'dal',
    'dal_select2',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
]

# Ini setlah folder dirubah jadi huruf kecil maka url juga dirubah huruf kecil kurikulum
ROOT_URLCONF = 'kurikulum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Ini juga dirubah jadi K Kecil
WSGI_APPLICATION = 'kurikulum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

    # 'default': dj_database_url.config(conn_max_age=600, ssl_require=True)

}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


#STATIC_URL = 'static/'


STATIC_URL = '/static/'
#STATICFILES_DIRS = [BASE_DIR / "static", ]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#STATIC_ROOT = BASE_DIR / 'staticfiles'
#STATIC_URL = '/static/'

# Pengaturan tambahan untuk WhiteNoise
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
