# Generated by Django 4.2.15 on 2024-08-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeBk', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=250)),
                ('acuan', models.CharField(choices=[('1', 'SN DIKTI'), ('2', 'CS2023'), ('3', 'Panduan Universitas'), ('4', 'Sumber Lain')], max_length=1)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Bahan Kajian',
            },
        ),
        migrations.CreateModel(
            name='CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeCpl', models.CharField(max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('unsur', models.CharField(choices=[('S', 'Sikap'), ('P', 'Pengetahuan'), ('K', 'Keterampilan')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Kode Capaian Pembelajaran Lulusan',
            },
        ),
        migrations.CreateModel(
            name='CPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeCpmk', models.CharField(max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.cpl')),
            ],
            options={
                'verbose_name_plural': 'Kode Capaian Pembelajaran Mata Kuliah',
            },
        ),
        migrations.CreateModel(
            name='CPMK_MK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.cpmk')),
            ],
            options={
                'verbose_name_plural': 'CPMK - MK',
            },
        ),
        migrations.CreateModel(
            name='PL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodePl', models.CharField(max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kode Profil Lulusan',
            },
        ),
        migrations.CreateModel(
            name='SUBCPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeSubCpmk', models.CharField(max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('cpmk_mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.cpmk_mk')),
            ],
            options={
                'verbose_name_plural': 'SUB CPMK',
            },
        ),
        migrations.CreateModel(
            name='MK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeMk', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('bk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.bk')),
                ('cpl', models.ManyToManyField(to='obe.cpl')),
            ],
            options={
                'verbose_name_plural': 'Nama Mata Kuliah',
            },
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='mk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.mk'),
        ),
        migrations.AddField(
            model_name='cpl',
            name='pl',
            field=models.ManyToManyField(to='obe.pl'),
        ),
        migrations.AddField(
            model_name='bk',
            name='cpl',
            field=models.ManyToManyField(to='obe.cpl'),
        ),
    ]
