# Generated by Django 4.2.15 on 2024-08-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpl',
            options={'verbose_name_plural': 'Capaian Pembelajaran Lulusan'},
        ),
        migrations.AlterModelOptions(
            name='cpmk',
            options={'verbose_name_plural': 'Capaian Pembelajaran Mata Kuliah'},
        ),
        migrations.AlterModelOptions(
            name='mk',
            options={'verbose_name_plural': 'Mata Kuliah'},
        ),
        migrations.AlterModelOptions(
            name='pl',
            options={'verbose_name_plural': 'Profil Lulusan'},
        ),
        migrations.AlterField(
            model_name='bk',
            name='kodeBk',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cpl',
            name='kodeCpl',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cpmk',
            name='kodeCpmk',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mk',
            name='kodeMk',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pl',
            name='kodePl',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subcpmk',
            name='kodeSubCpmk',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
