# Generated by Django 4.2.15 on 2024-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0002_alter_cpl_options_alter_cpmk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mk',
            name='semester',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mk',
            name='sks',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
