# Generated by Django 4.2.15 on 2024-08-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0003_mk_semester_mk_sks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mk',
            name='sks',
            field=models.SmallIntegerField(),
        ),
    ]
