# Generated by Django 4.2.15 on 2024-08-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0004_alter_mk_sks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPL_CPMK_MK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbkm', models.BooleanField(blank=True, default=False, null=True)),
                ('bobotMbkm', models.SmallIntegerField(blank=True, null=True)),
                ('partisipasi', models.BooleanField(blank=True, default=False, help_text='Komponen Kehadiran/Quiz', null=True)),
                ('bobotPartisipasi', models.SmallIntegerField(blank=True, null=True)),
                ('observasi', models.BooleanField(blank=True, default=False, help_text='Praktek/Tugas', null=True)),
                ('bobotObservasi', models.SmallIntegerField(blank=True, null=True)),
                ('unjukKerja', models.BooleanField(blank=True, default=False, help_text='Presentasi', null=True)),
                ('bobotUnjukKerja', models.SmallIntegerField(blank=True, null=True)),
                ('uts', models.BooleanField(blank=True, default=False, null=True)),
                ('bobotUts', models.SmallIntegerField(blank=True, null=True)),
                ('uas', models.BooleanField(blank=True, default=False, null=True)),
                ('bobotUas', models.SmallIntegerField(blank=True, null=True)),
                ('tesLisan', models.BooleanField(blank=True, default=False, help_text='Tugas Kelompok', null=True)),
                ('bobottesLisan', models.SmallIntegerField(blank=True, null=True)),
                ('tahapPenilaian', models.CharField(max_length=250)),
                ('teknikPenilaian', models.CharField(max_length=250)),
                ('instrumen', models.CharField(max_length=250)),
                ('kriteria', models.CharField(max_length=250)),
                ('bobot', models.CharField(max_length=250)),
                ('aktif', models.BooleanField(default=True)),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.cpl')),
                ('cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.cpmk')),
                ('mk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.mk')),
            ],
            options={
                'verbose_name_plural': 'CPL - CPMK - MK',
            },
        ),
    ]
