# Generated by Django 4.2.15 on 2024-08-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0005_cpl_cpmk_mk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpl_cpmk_mk',
            name='bobot',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cpl_cpmk_mk',
            name='instrumen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cpl_cpmk_mk',
            name='kriteria',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cpl_cpmk_mk',
            name='tahapPenilaian',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cpl_cpmk_mk',
            name='teknikPenilaian',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
