# Generated by Django 4.2.15 on 2024-08-31 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0006_alter_cpl_cpmk_mk_bobot_alter_cpl_cpmk_mk_instrumen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bk',
            options={'verbose_name_plural': 'BK (Bahan Kajian)'},
        ),
        migrations.AlterModelOptions(
            name='cpl',
            options={'verbose_name_plural': 'CPL (Capaian Pembelajaran Lulusan)'},
        ),
        migrations.AlterModelOptions(
            name='cpmk',
            options={'verbose_name_plural': 'CPMK (Capaian Pembelajaran Mata Kuliah)'},
        ),
        migrations.AlterModelOptions(
            name='mk',
            options={'verbose_name_plural': 'MK (Mata Kuliah)'},
        ),
        migrations.AlterModelOptions(
            name='pl',
            options={'verbose_name_plural': 'PL (Profil Lulusan)'},
        ),
        migrations.RemoveField(
            model_name='subcpmk',
            name='cpmk_mk',
        ),
        migrations.AddField(
            model_name='subcpmk',
            name='cpl_cpmk_mk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obe.cpl_cpmk_mk'),
        ),
    ]
