# Generated by Django 4.2.15 on 2024-09-01 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0007_alter_bk_options_alter_cpl_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcpmk',
            name='cpl_cpmk_mk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obe.cpl_cpmk_mk'),
        ),
        migrations.AlterField(
            model_name='subcpmk',
            name='kodeSubCpmk',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
