# Generated by Django 4.2.15 on 2024-09-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obe", "0008_alter_subcpmk_cpl_cpmk_mk_alter_subcpmk_kodesubcpmk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcpmk",
            name="cpl_cpmk_mk",
            field=models.ForeignKey(
                help_text="Ketik Kode CPMK dan MK pada kotak search di atas untuk mempermudah penginputan",
                on_delete=django.db.models.deletion.CASCADE,
                to="obe.cpl_cpmk_mk",
            ),
        ),
    ]
