# Generated by Django 4.2.15 on 2024-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0010_remove_mk_cpl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobot',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobotMbkm',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobotObservasi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobotPartisipasi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobotUas',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobotUnjukKerja',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobotUts',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='bobottesLisan',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='instrumen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='kriteria',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='mbkm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='observasi',
            field=models.BooleanField(blank=True, default=False, help_text='Praktek/Tugas', null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='partisipasi',
            field=models.BooleanField(blank=True, default=False, help_text='Komponen Kehadiran/Quiz', null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='tahapPenilaian',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='teknikPenilaian',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='tesLisan',
            field=models.BooleanField(blank=True, default=False, help_text='Tugas Kelompok', null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='uas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='unjukKerja',
            field=models.BooleanField(blank=True, default=False, help_text='Presentasi', null=True),
        ),
        migrations.AddField(
            model_name='cpmk_mk',
            name='uts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
