# Generated by Django 4.2.15 on 2024-09-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0011_cpmk_mk_bobot_cpmk_mk_bobotmbkm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUBCPMK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeSubCpmk', models.CharField(blank=True, max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('cpmk_mk', models.ForeignKey(help_text='Ketik Kode CPMK dan MK pada kotak search di atas untuk mempermudah penginputan', on_delete=django.db.models.deletion.CASCADE, to='obe.cpmk_mk')),
            ],
            options={
                'verbose_name_plural': 'SUB CPMK',
            },
        ),
    ]
