# Generated by Django 4.2.15 on 2024-09-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0012_subcpmk2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcpmk2',
            options={'verbose_name_plural': 'SUB CPMK2'},
        ),
    ]
