# Generated by Django 4.2.15 on 2024-09-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0013_alter_subcpmk2_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcpmk',
            name='cpl_cpmk_mk',
        ),
        migrations.AlterModelOptions(
            name='bk',
            options={'verbose_name_plural': '3. BK (Bahan Kajian)'},
        ),
        migrations.AlterModelOptions(
            name='cpl',
            options={'verbose_name_plural': '2. CPL (Capaian Pembelajaran Lulusan)'},
        ),
        migrations.AlterModelOptions(
            name='cpmk',
            options={'verbose_name_plural': '4. CPMK (Capaian Pembelajaran Mata Kuliah)'},
        ),
        migrations.AlterModelOptions(
            name='cpmk_mk',
            options={'verbose_name_plural': '6. CPMK - MK'},
        ),
        migrations.AlterModelOptions(
            name='mk',
            options={'verbose_name_plural': '5. MK (Mata Kuliah)'},
        ),
        migrations.AlterModelOptions(
            name='pl',
            options={'verbose_name_plural': '1. PL (Profil Lulusan)'},
        ),
        migrations.AlterModelOptions(
            name='subcpmk2',
            options={'verbose_name_plural': '7. SUB CPMK'},
        ),
        migrations.DeleteModel(
            name='CPL_CPMK_MK',
        ),
        migrations.DeleteModel(
            name='SUBCPMK',
        ),
    ]
