# Generated by Django 4.2.15 on 2024-09-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0014_remove_subcpmk_cpl_cpmk_mk_alter_bk_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bk',
            name='cpl',
            field=models.ManyToManyField(related_name='bk_cpl', to='obe.cpl'),
        ),
        migrations.AlterField(
            model_name='cpl',
            name='pl',
            field=models.ManyToManyField(related_name='cpl_pl', to='obe.pl'),
        ),
        migrations.AlterField(
            model_name='cpmk',
            name='cpl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmk_cpl', to='obe.cpl'),
        ),
        migrations.AlterField(
            model_name='cpmk_mk',
            name='cpmk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmk_mk_cpmk', to='obe.cpmk'),
        ),
        migrations.AlterField(
            model_name='cpmk_mk',
            name='mk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmk_mk_mk', to='obe.mk'),
        ),
        migrations.AlterField(
            model_name='mk',
            name='bk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mk_bk', to='obe.bk'),
        ),
        migrations.AlterField(
            model_name='subcpmk2',
            name='cpmk_mk',
            field=models.ForeignKey(help_text='Ketik Kode CPMK dan MK pada kotak search di atas untuk mempermudah penginputan', on_delete=django.db.models.deletion.CASCADE, related_name='subcpmk2_cpmk_mk', to='obe.cpmk_mk'),
        ),
    ]
