# Generated by Django 4.2.15 on 2024-09-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0015_alter_bk_cpl_alter_cpl_pl_alter_cpmk_cpl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpmk',
            name='cpl',
        ),
    ]
